# Site
title: 'Will It Compile?'
description: 'Weblog about software development and webdesign'
url: 'https://willitcompile.net'
repository: TangChr/willitcompile.net

# Author
author:
  name: 'Christian Tang Christensen'
  
timezone: Europe/Copenhagen
  
# Build
environment: production
baseurl: 'https://willitcompile.net/'
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.cmd
  - vendor

# Other
gems:
  - jekyll-feed
  - jekyll-sitemap
