# Site Information
title: "Will It Compile?"
generator: "Jekyll, gh-pages"
url: http://willitcompile.net
description: "Weblog about software development and webdesign"

# Author
author:
  name: "Christian Tang Christensen"
  uri: http://seaweed.dk

timezone: Europe/Copenhagen
  
# Build settings
baseurl: /
destination: _site
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  
# Excludes
exclude: ["serve.cmd", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]