# Site Information
title: "Will It Compile?"
generator: "Jekyll, gh-pages"
url: http://willitcompile.net
description: "Weblog about software development and webdesign"

author:
  name: "Christian Tang Christensen"
  uri: http://seaweed.dk
  twitter: TangChr

# Build settings
baseurl: /
destination: _site
permalink: pretty
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  hard_wrap: false
  
# Excludes
exclude: ["serve.cmd", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]