# Site Information
title: " Will It Compile?"
generator: "Jekyll, gh-pages"
url: http://willitcompile.net
description: "Weblog about software development and webdesign"

author:
  name: "Christian Tang Christensen"
  uri: http://seaweed.dk
  twitter: TangChr
  github: TangChr

# Excludes
exclude: ["serve.cmd", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Settings
baseurl: /
permalink: pretty
relative_permalinks: false
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM
  hard_wrap: false

sass:
    style: expanded