# Site Information
title: "implied.dk"
tagline: "Implied Code"
author: "Christian Tang Christensen"
generator: "Jekyll, gh-pages"
url: http://implied.dk

# Excludes
exclude: ["serve.cmd", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Settings
baseurl: /
permalink: pretty
relative_permalinks: true
markdown: redcarpet
highlighter: pygments
sass:
    style: expanded