# Site
title: 'Will It Compile?'
description: 'Weblog about software development and webdesign'
url: 'http://willitcompile.net'

# Repository
repo:
  github_url: 'https://github.com/TangChr/willitcompile.net'

# Author
author:
  name: 'Christian Tang Christensen'
  
timezone: Europe/Copenhagen
  
# Build
environment: production
baseurl: '/'
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.cmd
  - vendor

# Other
gems:
  - jekyll-feed
  - jekyll-sitemap