# Site Information
title: "Will It Compile?"
generator: "Jekyll, gh-pages"
url: http://willitcompile.net
description: "Weblog about software development and webdesign"

# Author
author:
  name: "Christian Tang Christensen"
  uri: http://seaweed.dk

timezone: Europe/Copenhagen
  
# Build settings
baseurl: /
destination: _site
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  
gems:
  - jekyll-feed
  - jekyll-sitemap
  
# Excludes
exclude: [CNAME, Gemfile, Gemfile.lock, serve.cmd, LICENSE, README.md]