# Site
title: "Will It Compile?"
description: 'Weblog about software development and webdesign'

# Repository
repo:
  name:      'willitcompile.net'
  github_url: 'https://github.com/TangChr/willitcompile.net'

url: http://willitcompile.net
baseurl: '/'
permalink: pretty
timezone: Europe/Copenhagen

# Author
author:
  name: 'Christian Tang Christensen'
  
# Build
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

environment: production

# Other
gems:
  - jekyll-feed
  - jekyll-sitemap
  
# Excludes
exclude: [CNAME, Gemfile, Gemfile.lock, serve.cmd, LICENSE, README.md]